name: propulse
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    # Core Dependencies
    - fastapi>=0.104.0
    - uvicorn>=0.24.0
    - streamlit>=1.28.0
    - pydantic>=2.4.2
    
    # Vector Database & Embeddings
    - faiss-cpu>=1.7.4
    - sentence-transformers>=2.2.2
    
    # Document Processing
    - python-docx>=1.0.0
    - python-multipart>=0.0.6
    - pypdf>=3.17.0
    
    # Google Cloud & AI
    - google-cloud-storage>=2.13.0
    - google-cloud-secret-manager>=2.16.4
    - google-cloud-logging>=3.8.0
    - google-generativeai>=0.8.0
    
    # Development & Testing
    - pytest>=7.4.3
    - pytest-cov>=4.1.0
    - black>=23.10.0
    - isort>=5.12.0
    - flake8>=6.1.0
    
    # Utilities
    - python-dotenv>=1.0.0
    - tenacity>=8.2.3
    - loguru>=0.7.2
    - tqdm>=4.66.1
    - markdown>=3.5.0 